name: 01 - hello #colcamos nombre del workflow

on: #definimos cuando se va a ejecutar el workflow
push: # en este ejemplo se ejecuta cuando se hace un push a la rama main
  branches: [main] # se ejecuta en la rama main

jobs: # definimos los jobs o tareas que se van a ejecutar en el workflow
  hello: #definimos el job o tarea aca puede ser cualquier nombre, recomendable que sea descriptivo
    runs-on: ubuntu-24.04 #definimos el entorno en el que se va a ejecutar el job se puede usar cualquier entorno, en este caso se usa ubuntu-24.04
    steps: # definimos los pasos que se van a ejecutar en el job

      - name: saludar #definimos el nombre del paso
        run: echo "Hello World" #definimos el script que se va a ejecutar en el paso

      - name: mostrar la fecha y hora #definimos el nombre del paso
        run: date # comando para mostrar la fecha y hora

      -  name: mostrar archivos disponibles
         run: ls -la # comando para mostrar los archivos disponibles
        